language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1.3
  - 2.2.0-preview1
env:
  - TARGET=redmine REDMINE_VERSION=2.3.4
  - TARGET=plugin  REDMINE_VERSION=2.3.4
  - TARGET=redmine REDMINE_VERSION=2.4.7
  - TARGET=plugin  REDMINE_VERSION=2.4.7
  - TARGET=redmine REDMINE_VERSION=2.5.3
  - TARGET=plugin  REDMINE_VERSION=2.5.3
  - TARGET=redmine REDMINE_VERSION=2.6.0
  - TARGET=plugin  REDMINE_VERSION=2.6.0
matrix:
  allow_failures:
    - rvm: 2.2.0-preview1
before_install: sh travis/before_install.sh
script: sh travis/exec_test.sh

