language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
env:
  - TARGET=redmine REDMINE_VERSION=2.5.3
  - TARGET=plugin  REDMINE_VERSION=2.5.3
  - TARGET=redmine REDMINE_VERSION=2.6.7
  - TARGET=plugin  REDMINE_VERSION=2.6.7
  - TARGET=redmine REDMINE_VERSION=3.0.5
  - TARGET=plugin  REDMINE_VERSION=3.0.5
  - TARGET=redmine REDMINE_VERSION=3.1.1
  - TARGET=plugin  REDMINE_VERSION=3.1.1
matrix:
  allow_failures:
    - rvm: 2.2
      env: TARGET=redmine REDMINE_VERSION=2.5.3
    - rvm: 2.2
      env: TARGET=plugin  REDMINE_VERSION=2.5.3
before_install: sh travis/before_install.sh
script: sh travis/exec_test.sh

