language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1.2
env:
  - TARGET=redmine REDMINE_VERSION=2.3.4
  - TARGET=plugin  REDMINE_VERSION=2.3.4
  - TARGET=redmine REDMINE_VERSION=2.4.6
  - TARGET=plugin  REDMINE_VERSION=2.4.6
  - TARGET=redmine REDMINE_VERSION=2.5.2
  - TARGET=plugin  REDMINE_VERSION=2.5.2
before_install: sh travis/before_install.sh
script: sh travis/exec_test.sh

